# Generated by Django 5.1.3 on 2024-11-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='Assigned_tp',
            new_name='Assigned_to',
        ),
    ]
